version: '3.8'

services:
  vue:
    build:
      context: .
      dockerfile: docker/Vue/Dockerfile
    container_name: vue-app
    ports:
      - "8080:80"
    networks:
      - game-network

networks:
  game-network:
    driver: bridge